apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.name" . }}-sa
  labels:
    {{- include "app.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.name" . }}-role
  labels:
    {{- include "app.labels" . | nindent 4 }}
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.name" . }}-rb
  labels:
    {{- include "app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.name" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "app.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
